### PR TITLE
Guard site submission concurrency

### LINKED ISSUE #143: Server crash when trying to expand a resource area
The server crashed when I tried to expand the oil section, or rather clicked on the expansion function, tried to allocate, but the neighboring copper was allocated as a new section and when trying to cancel the expansion of the site, the server crashed with an error:

```
98455.947 Error MainLoop.cpp:1284: Exception at tick 6052938: The mod YARM - Resource Monitor (0.8.203) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event YARM::on_gui_click (ID 1)
__YARM__/resmon.lua:550: attempt to index local 'site' (a nil value)
stack traceback:
        __YARM__/resmon.lua:550: in function 'submit_site'
        __YARM__/resmon.lua:1137: in function 'expand_site'
        __YARM__/resmon.lua:1271: in function <__YARM__/resmon.lua:1259>
98455.948 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The mod YARM - Resource Monitor (0.8.203) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event YARM::on_gui_click (ID 1)
__YARM__/resmon.lua:550: attempt to index local 'site' (a nil value)
stack traceback:
        __YARM__/resmon.lua:550: in function 'submit_site'
        __YARM__/resmon.lua:1137: in function 'expand_site'
        __YARM__/resmon.lua:1271: in function <__YARM__/resmon.lua:1259>"
98455.949 Info ServerMultiplayerManager.cpp:796: updateTick(6052938) changing state from(InGame) to(Failed)
98455.963 Quitting: multiplayer error.
```

### PR DESCRIPTION
**Pull request by narc0tiq**
It is possible for the game to attempt to submit "the current site" when there is no current site (see #143 for an example) so just make sure that `submit_site` doesn't try to do anything if there is no current site.

Fixes #143

### CODE REVIEW

File: resmon.lua [hunk 1]
```diff
@@ -1512,7 +1514,7 @@ function resmon.on_click.expand_site(event)
          site cleans up the expansion-related variables on the site) or if we were adding a new site
          and decide to expand an existing one
     --]]
-    if are_we_cancelling_expand or player_data.current_site then
+    if are_we_cancelling_expand and player_data.current_site then
```
Comment (narc0tiq) [inline resmon.lua:1517]: Honestly, I suspect just patching this one would fix the actual issue *but* it's safer for `submit_site` to actually check its input before it works on it.
